algo-LoL/src/Entity/Champion.php
<?php

namespace App\Entity;

use App\Repository\ChampionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChampionRepository::class)
 */
class Champion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="champions")
     */
    private $users;

    /**
     * @ORM\ManyToMany(targetEntity=Favorite::class, mappedBy="champions")
     */
    private $favorites;

    /**
     * @ORM\ManyToMany(targetEntity=Prefer::class, mappedBy="champions")
     */
    private $prefers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_role;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $second_role;



    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->prefers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addChampion($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeChampion($this);
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->addChampion($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->removeElement($favorite)) {
            $favorite->removeChampion($this);
        }

        return $this;
    }

    /**
     * @return Collection|Prefer[]
     */
    public function getPrefers(): Collection
    {
        return $this->prefers;
    }

    public function addPrefer(Prefer $prefer): self
    {
        if (!$this->prefers->contains($prefer)) {
            $this->prefers[] = $prefer;
            $prefer->addChampion($this);
        }

        return $this;
    }

    public function removePrefer(Prefer $prefer): self
    {
        if ($this->prefers->removeElement($prefer)) {
            $prefer->removeChampion($this);
        }

        return $this;
    }

    public function getFirstRole(): ?string
    {
        return $this->first_role;
    }

    public function setFirstRole(string $first_role): self
    {
        $this->first_role = $first_role;

        return $this;
    }

    public function getSecondRole(): ?string
    {
        return $this->second_role;
    }

    public function setSecondRole(?string $second_role): self
    {
        $this->second_role = $second_role;

        return $this;
    }
}

algo-LoL/src/Form/ChampionType.php
<?php

namespace App\Form;

use App\Entity\Champion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChampionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, [
                'label' => 'Nom du champion',
            ])
            ->add('image', null, [
                'label' => 'Image du champion',
            ])
            ->add('first_role', null, [
                'label' => 'Lane principale',
            ])
            ->add('second_role', null, [
                'label' => 'Lane secondaire',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Champion::class,
        ]);
    }
}

algo-LoL/src/Controller/ChampionController.php
<?php

namespace App\Controller;

use App\Entity\Champion;
use App\Form\ChampionType;
use App\Repository\ChampionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/champion")
 */
class ChampionController extends AbstractController
{
    /**
     * @Route("/", name="champion_list", methods={"GET"})
     */
    public function index(ChampionRepository $championRepository): Response
    {
        return $this->render('champion/list.html.twig', [
            'champions' => $championRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{name}", name="champion_show", methods={"GET"})
     */
    public function show(Champion $champion): Response
    {
        return $this->render('champion/show.html.twig', [
            'champion' => $champion,
        ]);
    }

    /**
     * @Route("/{name}/edit", name="champion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Champion $champion): Response
    {
        $form = $this->createForm(ChampionType::class, $champion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('champion_list');
        }

        return $this->render('champion/edit.html.twig', [
            'champion' => $champion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{name}", name="champion_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Champion $champion): Response
    {
        if ($this->isCsrfTokenValid('delete'.$champion->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($champion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('champion_list');
    }
}

algo-LoL/templates/champion/admin/add_champ.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<main class="admin main">

    <div class="title-page">
        <h1>Ajouter un champion</h1>
    </div>
<a class="return" href="{{ path('admin') }}">Retournez au tableau Administrateur</a> 
    <section class="board add">
        <div class="content-form">
            {{ form_start(form) }}
            {{ form_widget(form) }} 
            <div class="button">
                <button class="btn-submit">{{ button_label|default('Ajouter') }}</button>
            </div>          
            {{ form_end(form) }}
        </div>
    </section>

</main>

{% endblock %}

algo-LoL/templates/champion/admin/champ_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<main class="admin main">
    <section class="searcher">
            <div class="content-item-div">
                <div class="title-champion">
                    <h1>Rechercher un champion</h1>
                </div>
                <div class="content-search-bar">
                    <div class="search-bar">
                        <input id="search" class="search" type="text" placeholder="Search" name="search" size="40" value="">
                    </div>
                </div>
            </div>
    </section>
    <section class="table-champ-list width-60 j-center">
        <table class="width-80">
            <caption>Liste des champions</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Icon</th>
                    <th>Nom</th>
                    <th>Rôle principal</th>
                    <th>Rôle secondaire</th>
                    <th>Modifier / Supprimer</th>
                </tr>
            </thead>
            <tbody>
                {% for champion in allChamps %}
                    <tr class="champ-info">
                        <td>{{ champion.id }}</td>
                        <td class="content-icon-champ">
                            <div class="icon-champ j-center">
                                <img src="/assets/images/champions/{{ champion.name }}.png" alt="">
                            </div>
                        </td>
                        <td class="champ-name">{{ champion.name }}</td>
                        <td>{{ champion.firstRole }}</td>
                        {% if champion.secondRole is empty() %}
                        <td>X</td>
                        {% else %}
                        <td>{{ champion.secondRole }}</td>
                        {% endif %}
                        <td class="param-box">
                            <div class="content-box">
                                <div class="modify-box"></div>
                                <div class="delete-box"></div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
</main>
{% endblock %}

algo-LoL/templates/champion/admin/delete_champ.html.twig
{% extends 'base.html.twig' %}

algo-LoL/templates/champion/admin/edit_champ.html.twig
{% extends 'base.html.twig' %}